<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Calculadora</title>
	<link rel="stylesheet" type="text/css" href="./style/style.css">
</head>

<body>
	<main>
		<h1 id="titulo">La calculadora de Brian :D</h1>
		<form action="api.php" method="post">
			<input type="text" id="op1" name=" num1" placeholder="Operador 1" required>
			<select name="op" id="ope">
				<option disabled>+,-,x,/</option>
				<option value="+">+</option>
				<option value="-">-</option>
				<option value="*">x</option>
				<option value="/">/</option>
			</select>
			<input type="text" id="op2" name="num2" placeholder="Operador 2">
			<input type="submit" name="calcular" value="calcular" id="calcular">
		</form>

		<p id="resultado">
			RESULTADO:
			<?php
			$res = $_GET['res'] ?? '';

			echo (!empty($res)) ? htmlspecialchars($res)
				: 'Sin resultados';

			?>
		</p>
	</main>

</body>

</html>